language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install nodejs
  - sudo apt-get install npm
  - sudo npm install -g mountebank --production

before_script:
  - mb &
  - curl -i -X POST -H 'Content-Type: application/json' -d@tests/mountebank_mocks/imposter.json http://localhost:2525/imposters
  - composer self-update
  - composer install

script:
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
